name: CI Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.8.3'
          host: ${{ matrix.os == 'windows-latest' ? 'windows' : 'linux' }}
          target: desktop
          arch: ${{ matrix.os == 'windows-latest' ? 'win64_msvc2022_64' : 'gcc_64' }}
          modules: 'qtbase'
          cache: true

      - name: List Qt archs
        if: matrix.os == 'ubuntu-latest'
        run: |
          if [ "${{ matrix.os }}" == "windows-latest" ]; then
            python3 -m aqt list-qt windows desktop --arch 6.8.3
          else
            python3 -m aqt list-qt linux desktop --arch 6.8.3
          fi

      - name: Install Linux dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgl1-mesa-dev libxkbcommon-x11-0

      - name: Configure and Build
        shell: bash
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release
          cmake --build . --config Release

      - name: Test executable
        shell: bash
        run: |
          cd build
          if [ "${{ matrix.os }}" == "windows-latest" ]; then
            ls -la Release/ || ls -la .
          else
            ls -la .
            ldd tourist_map || true
          fi